packages:
    - packages/*
    - demos/*

ignoredBuiltDependencies:
    - protobufjs

onlyBuiltDependencies:
    - "@firebase/util"
    - "@scarf/scarf"
    - "@swc/core"
    - better-sqlite3
    - unrs-resolver
